/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bluemoon.vistas;

import bluemoon.dao.GuiaEntradaDAO;
import bluemoon.dao.GuiaSalidaDAO;
import bluemoon.model.Conexion;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Guias extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Guias() {
        initComponents();
        CargarGuiasEntrada();
    }
    
    public  void CargarGuiasEntrada(){
        DefaultTableModel objTabla = new DefaultTableModel();
        
        tblGuias.setModel(objTabla);
        objTabla.setRowCount(0);
        objTabla.addColumn("ID_Guía");
        objTabla.addColumn("Fecha");
        objTabla.addColumn("Observaciones");
        objTabla.addColumn("ID_Proveedor");
        objTabla.addColumn("ID_Factura");
        
        List<Vector> guias = GuiaEntradaDAO.findAll();
        
        for(Vector vec : guias)
        {
            objTabla.addRow(vec);
        }
        
    }
    
     public  void CargarGuiasSalida(){
        DefaultTableModel objTabla = new DefaultTableModel();
        
        tblGuias.setModel(objTabla);
        objTabla.setRowCount(0);
        objTabla.addColumn("ID_Guía");
        objTabla.addColumn("Fecha");
        objTabla.addColumn("Observaciones");
        
        List<Vector> guias = GuiaSalidaDAO.findAll();
        
        for(Vector vec : guias)
        {
            objTabla.addRow(vec);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtBuscar = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGuias = new javax.swing.JTable();
        cbxTipoGuia = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(127, 138, 209));

        txtBuscar.setBorder(null);
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Buscar guías:");

        tblGuias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblGuias);

        cbxTipoGuia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Salida" }));
        cbxTipoGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoGuiaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Tipo de guía:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxTipoGuia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxTipoGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed

    }//GEN-LAST:event_txtBuscarKeyPressed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        //CargarInventario("select DET_INVENTARIO.ID_PRODUCTO, DET_INVENTARIO.ID_ALMACEN, DET_INVENTARIO.CANTIDAD, PRODUCTO.NOMBRE_PRODUCTO from DET_INVENTARIO, PRODUCTO"
        //    + " WHERE DET_INVENTARIO.ID_PRODUCTO = PRODUCTO.ID_PRODUCTO AND PRODUCTO.NOMBRE_PRODUCTO LIKE '%" + txtBuscar.getText() + "%'");
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void cbxTipoGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoGuiaActionPerformed
        if(cbxTipoGuia.getSelectedItem().toString().equals("Entrada")){
            CargarGuiasEntrada();
        }else{
            CargarGuiasSalida();
        }
    }//GEN-LAST:event_cbxTipoGuiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxTipoGuia;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGuias;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
