
package bluemoon.vistas;

import bluemoon.dao.PedidoCompraDAO;
import bluemoon.model.Conexion;
import bluemoon.model.PedidoCompra;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class PedidosCompra extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public PedidosCompra() {
        initComponents();
        CargarProductos();
        CargarProveedores();
        CargarPedidos();
    }
    
    public void CargarPedidos(){
        DefaultTableModel objTabla = new DefaultTableModel();
        
        tblPedidos.setModel(objTabla);
        objTabla.setRowCount(0);
        objTabla.addColumn("ID_Pedido");
        objTabla.addColumn("ID_Proveedor");
        objTabla.addColumn("ID_Producto");
        objTabla.addColumn("Precio");
        objTabla.addColumn("Cantidad");
        
        List<Vector> listaPedidos = PedidoCompraDAO.findAll();
        
        for(Vector v : listaPedidos)
        {
            objTabla.addRow(v);
        }
    }
    
    public void CargarProductos(){
        DefaultComboBoxModel objCbo = new DefaultComboBoxModel();
        
        cbxProducto.setModel(objCbo);
        
        ResultSet resProd = Conexion.Consulta("select * from producto");
        
        try {
            while(resProd.next()){
                
                objCbo.addElement(resProd.getString(2));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la consulta de la tablas.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void CargarProveedores(){
        DefaultComboBoxModel objCbo = new DefaultComboBoxModel();
        
        cbxProveedor.setModel(objCbo);
        
        ResultSet resProv = Conexion.Consulta("select * from proveedor");
        
        try {
            while(resProv.next()){
                
                objCbo.addElement(resProv.getString(3));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error en la consulta de la tablas.","Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public String BuscarIdProv(String nombre) throws SQLException{
        PreparedStatement pstProv = Conexion.getConexion().prepareStatement("SELECT * FROM PROVEEDOR WHERE NOMBRE_PROVEEDOR = ?");
        pstProv.setString(1, nombre);
        ResultSet res = pstProv.executeQuery();
         
        String id = "";
        
        while(res.next()){        
            id = res.getString(1);
        }
        return id;
    }
    
    public String BuscarIdProd(String nombre) throws SQLException{
        PreparedStatement pst = Conexion.getConexion().prepareStatement("SELECT * FROM PRODUCTO WHERE NOMBRE_PRODUCTO = ?");
        pst.setString(1, nombre);
        ResultSet res = pst.executeQuery();
         
        String id = "";
        
        while(res.next()){        
            id = res.getString(1);
        }
        return id;
    }
    
    public double BuscarPrecio(String id) throws SQLException{
        PreparedStatement pst = Conexion.getConexion().prepareStatement("SELECT * FROM PRODUCTO WHERE ID_PRODUCTO = ?");
        pst.setString(1, id);
        ResultSet res = pst.executeQuery();
         
        double precio = 0.0;
        
        while(res.next()){
            precio = res.getDouble(5);
        }
        return precio;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblPedidos = new javax.swing.JTable();
        txtBuscarPedido = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtCantidadPedido = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        cbxProveedor = new javax.swing.JComboBox<>();
        btnAgregarPedido = new javax.swing.JButton();
        cbxProducto = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(127, 138, 209));
        setForeground(new java.awt.Color(51, 255, 204));

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblPedidos);

        txtBuscarPedido.setBorder(null);
        txtBuscarPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarPedidoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarPedidoKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Buscar pedido:");

        jPanel4.setBackground(new java.awt.Color(127, 138, 209));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel25.setText("Datos del pedido");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("Producto:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Cantidad:");

        txtCantidadPedido.setBorder(null);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel31.setText("Proveedor:");

        btnAgregarPedido.setBackground(new java.awt.Color(255, 207, 38));
        btnAgregarPedido.setText("Realizar pedido");
        btnAgregarPedido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 207, 38)));
        btnAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAgregarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                            .addComponent(txtCantidadPedido)
                            .addComponent(cbxProveedor, 0, 224, Short.MAX_VALUE))))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(cbxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtCantidadPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnAgregarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(233, 233, 233)
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtBuscarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(278, 278, 278))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGap(24, 24, 24)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtBuscarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
        try {
            //captura de valores
            String idProv = BuscarIdProv(cbxProveedor.getSelectedItem().toString());
            String idProd = BuscarIdProd(cbxProducto.getSelectedItem().toString());
            int cantidad = Integer.parseInt(txtCantidadPedido.getText());
            
            //calcular el precio
            double precio = cantidad * BuscarPrecio(idProd);
            
            //ManejoPedidosCompra.InsertarPedido(idProv, idProd, precio, cantidad);
        } catch (SQLException ex) {
            Logger.getLogger(PedidosCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        CargarPedidos();
        
    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    private void txtBuscarPedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPedidoKeyReleased
        
    }//GEN-LAST:event_txtBuscarPedidoKeyReleased

    private void txtBuscarPedidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarPedidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarPedidoKeyPressed

    private void tblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblPedidosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPedido;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblPedidos;
    private javax.swing.JTextField txtBuscarPedido;
    private javax.swing.JTextField txtCantidadPedido;
    // End of variables declaration//GEN-END:variables
}
